/*
 * DialogoFondo.java
 *
 * Created on 21 de febrero de 2007, 19:50
 */

package kchalkboard.view;

/**
 *
 * @author  eduardo
 */
public class DialogoFondo extends javax.swing.JDialog {
    
    int fondo;
    boolean ok;
    /**
     * Creates new form DialogoFondo
     */
    public DialogoFondo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        ok = false;
    }
    
    
    public void setValorFondo(int f) {
        
        fondo = f;
        
        ajustarBotones();
    }
    
    public int getFondo() {
        
        return(fondo);
    }
    
    private void ajustarBotones() {
        
        switch(fondo) {
        
            case 1: jRadioButton1.setSelected(true);
                    break;
                    
            case 2: jRadioButton2.setSelected(true);
                    break;
                                
            case 3: jRadioButton3.setSelected(true);
                    break;
                                
            case 4: jRadioButton4.setSelected(true);
                    break;                               

        }
    }
    
    public int leerBotones() {
        
        int valor;
        
        valor = 1;
        
        if(jRadioButton1.isSelected())
            valor = 1;
        else 
            if(jRadioButton2.isSelected())
               valor = 2;
            else 
               if(jRadioButton3.isSelected())
                  valor = 3;
                else 
                   if(jRadioButton4.isSelected())
                      valor = 4;

        return(valor);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Elegir un fondo");

        jLabel1.setText("Fondos disponibles");

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Pizarr—n Tradicional negro");
        jRadioButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Pizarra moderna blanca");
        jRadioButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Rotafolio de papel");
        jRadioButton3.setMargin(new java.awt.Insets(0, 0, 0, 0));

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Hoja de cuaderno");
        jRadioButton4.setMargin(new java.awt.Insets(0, 0, 0, 0));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(jButton1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 128, Short.MAX_VALUE)
                        .add(jButton2))
                    .add(layout.createSequentialGroup()
                        .add(81, 81, 81)
                        .add(jLabel1))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jRadioButton1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jRadioButton2))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jRadioButton3))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jRadioButton4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(23, 23, 23)
                .add(jRadioButton1)
                .add(9, 9, 9)
                .add(jRadioButton2)
                .add(9, 9, 9)
                .add(jRadioButton3)
                .add(10, 10, 10)
                .add(jRadioButton4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 66, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1)
                    .add(jButton2)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrar(boolean tok) {
        
    
         ok = tok;
         this.setVisible(false);
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
        
        fondo = leerBotones();
        this.cerrar(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
        
        this.cerrar(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    
    public boolean ok() {
    
        return(ok);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    // End of variables declaration//GEN-END:variables
    
}
